# Generated by Django 5.2.8 on 2025-11-20 19:11

import django.contrib.auth.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(blank=True, max_length=150, null=True, unique=True, verbose_name='نام کاربری')),
                ('phone_number', models.CharField(help_text='شماره موبایل باید 11 رقم باشد (مثال: 09123456789)', max_length=11, unique=True, verbose_name='شماره موبایل')),
                ('otp_code', models.CharField(blank=True, max_length=4, null=True, verbose_name='کد OTP')),
                ('otp_code_created', models.DateTimeField(blank=True, null=True, verbose_name='زمان ایجاد کد OTP')),
                ('role', models.CharField(choices=[('SUPER_ADMIN', 'سوپر ادمین'), ('SITE_ADMIN', 'مدیر سایت'), ('CUSTOMER', 'مشتری')], default='CUSTOMER', max_length=20, verbose_name='نقش کاربری')),
                ('is_phone_verified', models.BooleanField(default=False, help_text='اگر این فیلد True باشد، شماره موبایل توسط مدیر تایید شده است', verbose_name='شماره موبایل تایید شده')),
                ('national_id', models.CharField(blank=True, max_length=10, null=True, verbose_name='کد ملی')),
                ('national_card_image', models.ImageField(blank=True, null=True, upload_to='national_cards/', verbose_name='عکس کارت ملی')),
                ('profile_completed', models.BooleanField(default=False, verbose_name='پروفایل تکمیل شده')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربران',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
