# Generated by Django 5.2.8 on 2025-11-21 14:52

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='birth_date',
            field=django_jalali.db.models.jDateField(blank=True, help_text='تاریخ تولد به شمسی', null=True, verbose_name='تاریخ تولد'),
        ),
    ]
