# Generated by Django migration

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_create_customer_profiles_for_existing_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, help_text='عکس پروفایل کاربر (اختیاری)', null=True, upload_to='avatars/', verbose_name='عکس پروفایل'),
        ),
    ]
