# Generated by Django 5.2.8 on 2025-12-20 13:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_wallet_bankcard_withdrawalrequest_systemsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepositRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, help_text='مبلغ واریز شده به ریال', max_digits=15, verbose_name='مبلغ')),
                ('tracking_number', models.CharField(help_text='شماره پیگیری تراکنش', max_length=50, verbose_name='شماره پیگیری')),
                ('deposit_date', models.DateField(verbose_name='تاریخ واریز')),
                ('receipt_image', models.ImageField(upload_to='deposit_receipts/', verbose_name='تصویر فیش واریزی')),
                ('status', models.CharField(choices=[('PENDING', 'در انتظار بررسی'), ('APPROVED', 'تایید شده'), ('REJECTED', 'رد شده'), ('COMPLETED', 'تکمیل شده')], default='PENDING', max_length=20, verbose_name='وضعیت')),
                ('request_code', models.CharField(db_index=True, help_text='کد منحصر به فرد درخواست', max_length=20, unique=True, verbose_name='کد درخواست')),
                ('admin_note', models.TextField(blank=True, help_text='یادداشت مدیر در مورد این درخواست', null=True, verbose_name='یادداشت مدیر')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposit_requests', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'درخواست واریز',
                'verbose_name_plural': 'درخواست\u200cهای واریز',
                'ordering': ['-created_at'],
            },
        ),
    ]
