# Generated by Django 5.2.8 on 2025-12-20 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_depositrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankcard',
            name='user',
        ),
        migrations.RemoveField(
            model_name='withdrawalrequest',
            name='bank_card',
        ),
        migrations.RemoveField(
            model_name='depositrequest',
            name='user',
        ),
        migrations.DeleteModel(
            name='SystemSettings',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='user',
        ),
        migrations.RemoveField(
            model_name='withdrawalrequest',
            name='user',
        ),
        migrations.DeleteModel(
            name='BankCard',
        ),
        migrations.DeleteModel(
            name='DepositRequest',
        ),
        migrations.DeleteModel(
            name='Wallet',
        ),
        migrations.DeleteModel(
            name='WithdrawalRequest',
        ),
    ]
