# Generated by Django 5.2.8 on 2025-12-28 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_withdrawalrequest_completed_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SystemSettings',
        ),
        migrations.AddField(
            model_name='wallet',
            name='pending_withdrawal_gold',
            field=models.DecimalField(decimal_places=3, default=0, help_text='موجودی طلا که در انتظار تایید برداشت است', max_digits=10, verbose_name='موجودی طلای مسدود شده'),
        ),
        migrations.AddField(
            model_name='wallet',
            name='pending_withdrawal_rial',
            field=models.DecimalField(decimal_places=0, default=0, help_text='موجودی ریالی که در انتظار تایید برداشت است', max_digits=15, verbose_name='موجودی ریالی مسدود شده'),
        ),
    ]
