# Generated by Django 5.2.8 on 2025-12-28 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_depositaccount'),
        ('wallet', '0003_delete_systemsettings_wallet_pending_withdrawal_gold_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepositAccountAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(choices=[('WITHDRAWAL', 'حساب کاربر درخواست برداشت'), ('DEPOSIT_ACCOUNT', 'حساب پیش\u200cفرض مدیر'), ('CUSTOM', 'حساب سفارشی')], max_length=20, verbose_name='نوع حساب')),
                ('custom_bank_name', models.CharField(blank=True, help_text='فقط برای نوع CUSTOM', max_length=100, null=True, verbose_name='نام بانک (سفارشی)')),
                ('custom_card_number', models.CharField(blank=True, help_text='فقط برای نوع CUSTOM', max_length=19, null=True, verbose_name='شماره کارت (سفارشی)')),
                ('custom_sheba_number', models.CharField(blank=True, help_text='فقط برای نوع CUSTOM', max_length=26, null=True, verbose_name='شماره شبا (سفارشی)')),
                ('amount', models.DecimalField(decimal_places=0, help_text='مبلغ واریز به این حساب (ریال)', max_digits=15, verbose_name='مبلغ')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='ترتیب نمایش حساب\u200cها', verbose_name='ترتیب')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('deposit_account', models.ForeignKey(blank=True, help_text='فقط برای نوع DEPOSIT_ACCOUNT', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deposit_assignments', to='settings.depositaccount', verbose_name='حساب پیش\u200cفرض')),
                ('deposit_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_assignments', to='wallet.depositrequest', verbose_name='درخواست واریز')),
                ('withdrawal_request', models.ForeignKey(blank=True, help_text='فقط برای نوع WITHDRAWAL', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deposit_assignments', to='wallet.withdrawalrequest', verbose_name='درخواست برداشت')),
            ],
            options={
                'verbose_name': 'تخصیص حساب واریز',
                'verbose_name_plural': 'تخصیص\u200cهای حساب واریز',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='DepositReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(help_text='شماره پیگیری تراکنش', max_length=50, verbose_name='شماره پیگیری')),
                ('deposit_date', models.DateField(verbose_name='تاریخ واریز')),
                ('receipt_image', models.ImageField(upload_to='deposit_receipts/', verbose_name='تصویر فیش واریزی')),
                ('amount', models.DecimalField(decimal_places=0, help_text='مبلغ واریز شده (ریال)', max_digits=15, verbose_name='مبلغ')),
                ('status', models.CharField(choices=[('PENDING', 'در انتظار بررسی'), ('APPROVED', 'تایید شده'), ('REJECTED', 'رد شده')], default='PENDING', max_length=20, verbose_name='وضعیت')),
                ('admin_note', models.TextField(blank=True, null=True, verbose_name='یادداشت مدیر')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('account_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='wallet.depositaccountassignment', verbose_name='حساب تخصیص داده شده')),
                ('deposit_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='wallet.depositrequest', verbose_name='درخواست واریز')),
            ],
            options={
                'verbose_name': 'فیش واریزی',
                'verbose_name_plural': 'فیش\u200cهای واریزی',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DepositWithdrawalLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, help_text='مبلغی که از این واریز به این برداشت اختصاص یافته (ریال)', max_digits=15, verbose_name='مبلغ')),
                ('auto_approved', models.BooleanField(default=False, help_text='آیا این برداشت به صورت خودکار تایید شده است؟', verbose_name='تایید خودکار')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('deposit_receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_links', to='wallet.depositreceipt', verbose_name='فیش واریزی')),
                ('withdrawal_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposit_links', to='wallet.withdrawalrequest', verbose_name='درخواست برداشت')),
            ],
            options={
                'verbose_name': 'ارتباط واریز-برداشت',
                'verbose_name_plural': 'ارتباطات واریز-برداشت',
                'ordering': ['-created_at'],
                'unique_together': {('deposit_receipt', 'withdrawal_request')},
            },
        ),
    ]
