# Generated by Django 5.2.8 on 2025-12-28 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_depositaccountassignment_depositreceipt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositrequest',
            name='deposit_date',
            field=models.DateField(blank=True, help_text='تاریخ واریز (در flow جدید اختیاری است)', null=True, verbose_name='تاریخ واریز'),
        ),
        migrations.AlterField(
            model_name='depositrequest',
            name='receipt_image',
            field=models.ImageField(blank=True, help_text='تصویر فیش واریزی (در flow جدید اختیاری است)', null=True, upload_to='deposit_receipts/', verbose_name='تصویر فیش واریزی'),
        ),
        migrations.AlterField(
            model_name='depositrequest',
            name='tracking_number',
            field=models.CharField(blank=True, help_text='شماره پیگیری تراکنش (در flow جدید اختیاری است)', max_length=50, null=True, verbose_name='شماره پیگیری'),
        ),
    ]
