# Generated by Django 5.2.8 on 2025-12-28 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_make_deposit_fields_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositaccountassignment',
            name='custom_owner_name',
            field=models.CharField(blank=True, help_text='فقط برای نوع CUSTOM', max_length=200, null=True, verbose_name='نام صاحب حساب (سفارشی)'),
        ),
    ]
