# Generated by Django 5.2.8 on 2025-12-24 13:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_type', models.CharField(choices=[('BUY', 'خرید'), ('SELL', 'فروش')], db_index=True, max_length=10, verbose_name='نوع معامله')),
                ('amount', models.DecimalField(decimal_places=3, help_text='مقدار طلا به گرم', max_digits=10, verbose_name='مقدار (گرم)')),
                ('price', models.DecimalField(decimal_places=0, help_text='قیمت هر گرم طلا در زمان معامله', max_digits=15, verbose_name='قیمت واحد (ریال)')),
                ('total', models.DecimalField(decimal_places=0, help_text='مبلغ کل معامله', max_digits=15, verbose_name='مبلغ کل (ریال)')),
                ('fee', models.DecimalField(decimal_places=0, default=0, help_text='کارمزد معامله', max_digits=15, verbose_name='کارمزد (ریال)')),
                ('status', models.CharField(choices=[('SUCCESS', 'موفق'), ('FAILED', 'ناموفق'), ('PENDING', 'در انتظار'), ('CANCELLED', 'لغو شده')], db_index=True, default='PENDING', max_length=20, verbose_name='وضعیت')),
                ('tracking_code', models.CharField(db_index=True, help_text='کد رهگیری منحصر به فرد معامله', max_length=20, unique=True, verbose_name='کد رهگیری')),
                ('invoice_number', models.CharField(db_index=True, help_text='شماره فاکتور معامله', max_length=20, unique=True, verbose_name='شماره فاکتور')),
                ('admin_note', models.TextField(blank=True, null=True, verbose_name='یادداشت مدیر')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'معامله',
                'verbose_name_plural': 'معاملات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(choices=[('BUY_LIMIT', 'خرید در قیمت پایین'), ('SELL_LIMIT', 'فروش در قیمت بالا')], db_index=True, max_length=20, verbose_name='نوع سفارش')),
                ('target_price', models.DecimalField(decimal_places=0, help_text='قیمتی که در آن سفارش اجرا می\u200cشود', max_digits=15, verbose_name='قیمت هدف (ریال)')),
                ('amount', models.DecimalField(decimal_places=3, help_text='مقدار طلا به گرم', max_digits=10, verbose_name='مقدار (گرم)')),
                ('status', models.CharField(choices=[('PENDING', 'در انتظار'), ('SUSPENDED', 'معلق'), ('EXECUTED', 'اجرا شده'), ('CANCELLED', 'لغو شده'), ('EXPIRED', 'منقضی شده')], db_index=True, default='PENDING', max_length=20, verbose_name='وضعیت')),
                ('expires_at', models.DateTimeField(blank=True, help_text='تاریخ انقضای سفارش (اختیاری)', null=True, verbose_name='تاریخ انقضا')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('executed_trade', models.OneToOneField(blank=True, help_text='معامله\u200cای که از این سفارش ایجاد شده', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order', to='trades.trade', verbose_name='معامله اجرا شده')),
            ],
            options={
                'verbose_name': 'سفارش هوشمند',
                'verbose_name_plural': 'سفارشات هوشمند',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GoldPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_base_price', models.DecimalField(decimal_places=0, help_text='قیمت پایه خرید هر گرم طلا به ریال', max_digits=15, verbose_name='قیمت پایه خرید (ریال)')),
                ('sell_base_price', models.DecimalField(decimal_places=0, help_text='قیمت پایه فروش هر گرم طلا به ریال', max_digits=15, verbose_name='قیمت پایه فروش (ریال)')),
                ('buy_margin', models.DecimalField(decimal_places=0, default=0, help_text='حاشیه سود خرید به ریال (اضافه می\u200cشود به قیمت پایه)', max_digits=15, verbose_name='حاشیه سود خرید (ریال)')),
                ('sell_margin', models.DecimalField(decimal_places=0, default=0, help_text='حاشیه سود فروش به ریال (اضافه می\u200cشود به قیمت پایه)', max_digits=15, verbose_name='حاشیه سود فروش (ریال)')),
                ('buy_final_price', models.DecimalField(decimal_places=0, help_text='قیمت نهایی خرید = قیمت پایه + حاشیه سود', max_digits=15, verbose_name='قیمت نهایی خرید (ریال)')),
                ('sell_final_price', models.DecimalField(decimal_places=0, help_text='قیمت نهایی فروش = قیمت پایه + حاشیه سود', max_digits=15, verbose_name='قیمت نهایی فروش (ریال)')),
                ('is_active', models.BooleanField(default=True, help_text='آیا این قیمت فعلی است؟ (فقط یک رکورد باید فعال باشد)', verbose_name='فعال')),
                ('source', models.CharField(choices=[('MANUAL', 'دستی'), ('API', 'API خارجی')], default='MANUAL', help_text='منبع قیمت (دستی یا API)', max_length=10, verbose_name='منبع')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ و زمان ثبت')),
                ('created_by', models.ForeignKey(blank=True, help_text='کاربری که این قیمت را ثبت کرده (برای قیمت\u200cهای دستی)', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ثبت شده توسط')),
            ],
            options={
                'verbose_name': 'قیمت طلا',
                'verbose_name_plural': 'قیمت\u200cهای طلا',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_active', '-created_at'], name='trades_gold_is_acti_500f05_idx'), models.Index(fields=['source', '-created_at'], name='trades_gold_source_3e81b5_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['user', '-created_at'], name='trades_trad_user_id_1f28fa_idx'),
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['status', '-created_at'], name='trades_trad_status_2a01b5_idx'),
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['trade_type', '-created_at'], name='trades_trad_trade_t_e0cc67_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', 'status', '-created_at'], name='trades_orde_user_id_66acb9_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_type', 'status', 'target_price'], name='trades_orde_order_t_1ee5b3_idx'),
        ),
    ]
