# Generated by Django 5.2.8 on 2025-12-31 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0003_fix_trades_fee_based_on_margin'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='margin_profit',
            field=models.DecimalField(decimal_places=0, default=0, help_text='سود حاصل از حاشیه سود (حاشیه سود × مقدار)', max_digits=15, verbose_name='سود حاشیه (ریال)'),
        ),
    ]
