# Generated by Django 5.2.8 on 2026-08-18 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0005_alter_goldprice_margin_help_texts'),
    ]

    operations = [
        migrations.AddField(
            model_name='goldprice',
            name='market_change',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='تغییر قیمت نماد بازار نسبت به قبل، به ریال', max_digits=15, null=True, verbose_name='تغییر بازار (ریال)'),
        ),
        migrations.AddField(
            model_name='goldprice',
            name='market_change_percent',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='درصد تغییر بازار'),
        ),
        migrations.AddField(
            model_name='goldprice',
            name='market_high',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True, verbose_name='بالاترین امروز (ریال)'),
        ),
        migrations.AddField(
            model_name='goldprice',
            name='market_low',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True, verbose_name='پایین‌ترین امروز (ریال)'),
        ),
        migrations.AddField(
            model_name='goldprice',
            name='market_price_time',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='زمان نرخ بازار'),
        ),
        migrations.AddField(
            model_name='goldprice',
            name='market_symbol_name',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='نام نماد بازار'),
        ),
    ]
