# Generated by Django 5.2.8 on 2025-12-23 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_phone_numbers', models.JSONField(default=list, help_text='لیست شماره موبایل مدیران برای دریافت پیامک (به صورت آرایه)', verbose_name='شماره مدیران')),
                ('gold_pickup_address', models.TextField(blank=True, help_text='آدرس مراجعه حضوری برای دریافت طلا', null=True, verbose_name='آدرس مراجعه حضوری')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
            ],
            options={
                'verbose_name': 'تنظیمات سیستم',
                'verbose_name_plural': 'تنظیمات سیستم',
            },
        ),
    ]
