# Generated by Django 5.2.8 on 2025-12-24 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='trades_enabled',
            field=models.BooleanField(default=True, help_text='اگر فعال باشد، کاربران می\u200cتوانند معامله انجام دهند', verbose_name='فعال بودن معاملات'),
        ),
    ]
