# Generated by Django 5.2.8 on 2025-12-28 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_systemsettings_trades_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepositAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(help_text='نام بانک (مثال: بانک ملت)', max_length=100, verbose_name='نام بانک')),
                ('owner_name', models.CharField(help_text='نام صاحب حساب (مثال: شرکت گلد تریدر)', max_length=200, verbose_name='نام صاحب حساب')),
                ('card_number', models.CharField(help_text='شماره کارت بانکی (16 رقم)', max_length=19, verbose_name='شماره کارت')),
                ('sheba_number', models.CharField(help_text='شماره شبا (24 رقم)', max_length=26, verbose_name='شماره شبا')),
                ('is_active', models.BooleanField(default=True, help_text='اگر فعال باشد، در پنل کاربری نمایش داده می\u200cشود', verbose_name='فعال')),
                ('order', models.IntegerField(default=0, help_text='ترتیب نمایش حساب\u200cها (عدد کمتر = اولویت بیشتر)', verbose_name='ترتیب نمایش')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
            ],
            options={
                'verbose_name': 'حساب بانکی واریز',
                'verbose_name_plural': 'حساب\u200cهای بانکی واریز',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
